### ISSUE TITLE
colabs/spacy/SpaCy_v3_and_W&B.ipynb takes to long

### ISSUE THREAD

**Issue by tcapelle** [wandb/examples#124]
### What happened?

[This nb](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/spacy/SpaCy_v3_and_W%26B.ipynb) takes 20minutes in a Colab Pro instance.
We could make it run faster (less epochs, 3500 should be fine).

**Comment by ash0ts** [comment]
I believe you are referring to [this nb](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/spacy/SpaCy_v3_and_W%26B.ipynb) @tcapelle

**Comment by tcapelle** [comment]
ohh yeah, too much copy pasting...
