### ISSUE TITLE
colabs/dsviz/W&B_Dataset_and_Predictions_Viz_Demo.ipynb broken imports

### ISSUE THREAD

**Issue by tcapelle** [wandb/examples#125]
### What happened?

[This nb](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/dsviz/W&B_Dataset_and_Predictions_Viz_Demo.ipynb), Produces a broken import in fastai V1:
```
ModuleNotFoundError: No module named 'fastai.callbacks'
```

**Comment by scottire** [comment]
Can you link the referenced nb in these issues so its easier to navigate to please :)

**Comment by tcapelle** [comment]
that would be very convenient indeed!
