### ISSUE TITLE
How to save model with estimator?

### ISSUE THREAD

**Issue by WuZhuoran** [wandb/examples#13]
I am now following the following example guide with `wandb` tensorflow example.

```python
# Init wandb
import wandb
from wandb.tensorflow import WandbHook
wandb.init(project="test", sync_tensorboard=True)
 Model instantiation code ...
# Log metrics with wandb
# If you are using tensorboard already, we will sync all the information from tensorboard and this isn't necessary.
# If you are using an estimator you can add our hook.
classifier.train(input_fn=train_input_fn, steps=100000, hooks=[WandbHook()])
# Save model to wandb
saver = tf.train.Saver()
saver.save(sess, os.path.join(wandb.run.dir, "model.ckpt"))
```

I found that I want to use the `saver` I need to get the `sess` variable.

But in my current training, I used `tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)` for training with `estimator`.

Now if I cannot get `session`, how to save the model in wandb? 

Thank you.

**Comment by charlesfrye** [comment]
Hey there @WuZhuoran! Just provide `model_dir=wandb.run.dir` to the call to [`tf.estimator.Estimator`](https://www.tensorflow.org/guide/estimator). This directs all the `.ckpt` files into the run directory, where we can detect and upload it.

Sorry for the delay in responding! This channel isn't closely monitored. The best place for asking questions about W&B is via our Intercom support channel: just click the speech bubble floating in the bottom-right-hand corner of the website.
