### ISSUE TITLE
`colabs/tables/AlphaFold_with_W&B_Align,_Fold,_Log.ipynb` takes to long

### ISSUE THREAD

**Issue by tcapelle** [wandb/examples#135]
### What happened?

[This is a slow notebook](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/tables/AlphaFold_with_W&B_Align,_Fold,_Log.ipynb), as the setup and querying of proteins takes a long time.

**Comment by staceysv** [comment]
just want to give some context: the notebook is _saved with pre-existing outputs_ precisely for this reason! it's a very very slow process to do this correctly/functionally, yep :)
we can add notes to warn the user and we can pick faster sequences if folks prefer.

**Comment by tcapelle** [comment]
Thanks @staceysv, we will label it as `long` and not test it regularly then
