### ISSUE TITLE
No module named 'wandb.tensorflow' temporally [Bug]: 

### ISSUE THREAD

**Issue by huangjiancong1** [wandb/examples#139]
### What happened?

Please tell us which example failed and why. Please link the wandb.ai logs if you have one.

It is very weried that I can import WandbHook after typing ` from wandb.tensorflow.` + "Tab" key
```
>>> from wandb.tensorflow import WandbHook
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wandb.tensorflow'

>>> from wandb.tensorflow.
### Output from using "Tap" key: wandb.tensorflow.WandbHook(
### utput from using "Tap" key: wandb.tensorflow.estimator_hook
### Output from using "Tap" key: wandb.tensorflow.log(

>>> from wandb.tensorflow import WandbHook
>>> 

```

I am using `Python 3.6.13`, `tensorflow 1.15.2`, and `wandb 0.12.9`

**Comment by tcapelle** [comment]
@Ayush would you mind taking a look at this?

**Comment by tcapelle** [comment]
Can I close this @ayulockin ?
