### ISSUE TITLE
[Bug]: examples/keras/keras-cnn-fashion -> `cannot import name 'tune' from 'wandb.sweeps.config'.`

### ISSUE THREAD

**Issue by ash0ts** [wandb/examples#152]
### Tell us what happened?

Hyperopt/tune sweeps was deprecated due to low usage. Either we should remove this example to prevent users from referring to this example or explicitly mention/use an older cli version which does support this. The latest cli version that does this is
`pip install wandb[sweeps]==0.10.24`

**Comment by ash0ts** [comment]
To be specific this refers to `sweep-tune-hyperopt.py`

**Comment by tcapelle** [comment]
we should probably remove it then. Does it get referenced in the docs?

**Comment by ash0ts** [comment]
I didn't see it in anywhere in the Ray documentation nor the Hyperparameter tuning documentation we have. We refer to the Keras project where it exists in the Keras documentation but we don't directly reference Ray nor `sweep-tune-hyperopt.py`/`sweep-tune-hyperopt.yaml`

**Comment by ash0ts** [comment]
I'll drop in a PR

**Comment by dcferreira** [comment]
The hyperopt example is referred to both in the collab introducing Sweeps (the "Try in Collab" button [here](https://docs.wandb.ai/guides/sweeps)), and in the [README of the examples](https://github.com/wandb/examples/blob/master/examples/keras/keras-cnn-fashion/README.md).
