### ISSUE TITLE
[Bug]: `colabs/datasets-predictions/Image_Classification_with_Tables.ipynb` Preview is broken

### ISSUE THREAD

**Issue by ash0ts** [wandb/examples#154]
### Tell us what happened?

Going to the [mentioned jupyter notebook](https://github.com/wandb/examples/blob/master/colabs/datasets-predictions/Image_Classification_with_Tables.ipynb) yields the below error.

Tested in Safari on Mac, Firefox on Mac, and Safari on iPad

<img width="1282" alt="Screen Shot 2022-01-05 at 5 36 12 PM" src="https://user-images.githubusercontent.com/93145909/148299391-17bb286f-1ff2-4f5b-ab09-85c9887944d9.png">

**Comment by tcapelle** [comment]
This is weird, it works on nbviewer:
https://nbviewer.org/github/wandb/examples/blob/master/colabs/datasets-predictions/Image_Classification_with_Tables.ipynb

**Comment by tcapelle** [comment]
I found the issue!!!!
When you have `:` character on headers the render fails!!! This is insane...

**Comment by tcapelle** [comment]
Thanks to @dynamicwebpaige this is issue is solved ✅
