### ISSUE TITLE
wandb with torch + TPU

### ISSUE THREAD

**Issue by ratthachat** [wandb/examples#17]
Hi!

Does wandb works with torch + TPU (XLA) ?
(Example code : https://github.com/patil-suraj/exploring-T5/blob/master/T5_on_TPU.ipynb )

Since model will be forked into 8 parallel processes for 8 TPU cores, 
where is the best place should I put `wandb.watch(model, log="all") ` ?

Thanks very much!

**Comment by charlesfrye** [comment]
Hi @ratthachat! The best place for asking questions about W&B is via our Intercom support channel: just click the speech bubble floating in the bottom-right-hand corner of the website.

We are working on support for runs on TPUs, but we do not have it at this time.
