### ISSUE TITLE
Save simple plain-text 

### ISSUE THREAD

**Issue by DanieleVeri** [wandb/examples#18]
Hi! I'm working on a text generation experiment.
I'm logging loss and accuracy and it's fine, I love wandb!
But once finished the training I would like to 'log' a sample o generated text and be able to see on the wandb UI.
I tried with `wandb.log({"generated": txt_gen})` but on the web UI i still see "No data submitted for tag generated".

**Comment by vanpelt** [comment]
The best way to log text is with our `wandb.Table` media object.  You can find more information here: https://docs.wandb.com/library/log#media

**Comment by DanieleVeri** [comment]
It worked fine! 
Thank you very much!

**Comment by DanieleVeri** [comment]
Just for information, I think that html is even better because you can preserve line break:
```python
wandb.log({"generated":  wandb.Html("<pre>"+txt_gen+"</pre>", inject=False)})
```
