### ISSUE TITLE
[Bug]: Python Train Sweep Doesn't Log

### ISSUE THREAD

**Issue by zanussbaum** [wandb/examples#194]
### Tell us what happened?

Following from this [example in the docs](https://docs.wandb.ai/ref/python/agent#examples), I'd expect [train_lib](https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-python/train_lib.py) to log as well.

Am I misunderstanding what's needed for the sweep? How does the agent know what metrics to report?

**Comment by tcapelle** [comment]
Hello! thanks you for posting this issue.

The example you posted is old and uses the `magic` flag to detect and infer logging for Keras. What is happening with `train_lib` is that it's actually not logging anything. What you can do to make it work, is pass the `WandbCallback` to the `fit` function`
```python
# callback setup
cbs = [WandbCallback(data_type='image')]
```
I would suggest checking the [sweeps QuickStart](https://docs.wandb.ai/guides/sweeps/quickstart) and to check our up-to-date [Keras sweeps colab](https://github.com/wandb/examples/blob/master/colabs/keras/Keras_param_opti_using_sweeps.ipynb).

**Comment by tcapelle** [comment]
Have you solved your issue? Feel free to reopen if you need more help.
