### ISSUE TITLE
Colab examples need a .finish or .join in between runs

### ISSUE THREAD

**Issue by charlesfrye** [wandb/examples#23]
I am making this change in the notebook examples in the [ml-class repo](http://github.com/lukas/ml-class), but wanted to sync up with y'all. We should agree on whether to use `.finish` or `.join` and then stick to it.

With the upgrade to CLIng, the behavior of wandb in a notebook has been changed sufficiently to necessitate some rewriting in notebooks with multiple runs.

For example, our [Simple Keras Integration](https://colab.research.google.com/drive/1WZI9C9l8-mzTSNS3mXS2zKzdz7N38jYO?usp=sharing) includes multiple runs. This means that when `wandb.init` is called for the second run, `wandb.join` is called on the earlier run at the same time, and both are output by the same cell.

This results in confusing output: the wandb-logged metrics and sparklines for the first run (`royal-water-3`) are not well-separated from the model architecture output for the second run (`peach-serenity-4`).

![image](https://user-images.githubusercontent.com/10442975/93394195-ac38b800-f828-11ea-9799-95bca43a6e8f.png)

**Comment by charlesfrye** [comment]
@ayulockin I think you were the author on most of these.

**Comment by charlesfrye** [comment]
It should be noted that `wandb.finish`/`.join` throws an error if there's not been an `init` since the last call.

This means we should be careful about where we place these calls.

With operations of this type, best practice in Jupyter is to structure cells to avoid errors.

For example, it would be preferred to keep the `.init` and `.join` in the same cell.

This is highly restrictive, but it ensures that folks don't stumble into an error while trying out our software for the first time.

**Comment by vanpelt** [comment]
You can also use the context manager which will do it automatically:

```
with wandb.init(...) as run:
   #stuff
```

**Comment by charlesfrye** [comment]
do we have the context manager in CLIng? I thought that hadn't made it yet.

**Comment by ayulockin** [comment]
You are right @charlesfrye. With the upgraded CLIng, these notebooks must be corrected. I will get this done. 

What would be the behaviour difference in the use of `.join` and `.finish`? But I guess using context manager would be interesting. It will visually look so much better with TensorFlow or PyTorch training loop.

**Comment by charlesfrye** [comment]
There should be no behavior difference between `join` and `finish`.

`finish` is newer and semantically more clear, but `join` is everywhere because it has been around for a while. I think we're trying to push folks more towards `finish` moving forward, so might as well change it over.

**Comment by ayulockin** [comment]
Then let's push them torwards `finish`. Agreed?

**Comment by charlesfrye** [comment]
wfm. if the context manager works in CLIng, then i say we should use that as much as possible as well.

for [the Keras example](https://colab.research.google.com/drive/1WZI9C9l8-mzTSNS3mXS2zKzdz7N38jYO?usp=sharing), the CM is a bit weird because you do log some summary metrics after finishing training, and you. take a look and lmk what you decide to do so i can match it.

**Comment by vanpelt** [comment]
Context should work: https://github.com/wandb/client-ng/blob/master/wandb/sdk/wandb_run.py#L1488-L1494

**Comment by charlesfrye** [comment]
This has been folded into #28: as we update and VC all the Colabs, `.finish` and the context manager will be incorporated.
