### ISSUE TITLE
[Request]: method of using sweep across machines with command line 

### ISSUE THREAD

**Issue by Ga-Lee** [wandb/examples#236]
### What is about?

Hello! 
I have some troubles in using wandb-sweep across several machines with command line.
After creating a sweep on one machine, where stores the sweep_yaml and train.py, I want to start an agent on another machine.
After login my wandb in the shell, will it work as I expect with the next command:
> wandb agent sweep_id  

How can the new agent know what function(defined in train.py )to perform after getting hyparameters from controller?
Feeling confused!
Looking forward to your reply and appreciate for your kindness!

**Comment by scottire** [comment]
Hello, 
Sorry that you're having trouble. Happy to help.
You just need to make sure you can run the `train.py` script from the location you call `wandb agent sweep_id`. That involves having the same environment and code across each machine, and calling the agent command in the correct directory.

**Comment by tcapelle** [comment]
Just to add more info:
- You need on each machine the training script and the Dataset. Basically you need to able to run `train.py` in each machine independently.
- You can also launch multiple agents on one machine: If you have 3 GPUs, you can call the agent 3 times from differents terminals/tmux and run 3 agents in parallel.
