### ISSUE TITLE
Simple TensorFlow Integration colab throws errors when multiple models are trained

### ISSUE THREAD

**Issue by charlesfrye** [wandb/examples#25]
@ayulockin: in [the TensorFlow example](https://colab.research.google.com/drive/126c1k5IfbQpE7dVmhnoDTdmFfC7CgJqg?usp=sharing), attempting to run [the training step](https://colab.research.google.com/drive/126c1k5IfbQpE7dVmhnoDTdmFfC7CgJqg#scrollTo=8yECjtzMwdHd) more than once, e.g. after tweaking the model parameters, gives the following TensorFlow error:

```python
ValueError: tf.function-decorated function tried to create variables on non-first call.
```

This [discussion on GitHub](https://github.com/tensorflow/tensorflow/issues/27120) includes a [possible solution](https://github.com/tensorflow/tensorflow/issues/27120#issuecomment-540071844), but I found that just dropping the decorators removed the error. Not sure if the code remains correct, though.

**Comment by ayulockin** [comment]
Hey @charlesfrye, in my understanding this is less of an error even though `ValueError` is raised. When a function decorated with `tf.function` is run, that function gets compiled into a callable TensorFlow graph. This lead to increased speed. 

Thus after you make some tweak in the model parameter you just have to run all the cells with `tf.function` decorator sequentially to avoid the error. The best practice would be to have all the functions decorated with `tf.function` in the same cell.

**Comment by charlesfrye** [comment]
We want to avoid, as much as possible, the opportunity for users to generate errors that they don't know how to resolve, especially due to execution order. We (either the `wandb` library or the authors of the Colabs) will be blamed for the errors, even if it's not our fault.

Speed isn't important in our examples -- it's more important for code to be 1) readable and 2) robust to execution order and small (intelligent) tweaks. This encourages users to play with the code and become engaged with the example. We especially want to encourage them to run small versions of the kinds of experiments they might run with W&B (e.g. changing lr).

Obviously we don't want to write code that is frustratingly slow, but that doesn't seem to be the case here.

Lastly, we wouldn't just want to put the decorated functions into a single cell, we'd also want to put them inside the same cell as any code that directly depends on their proximal execution -- i.e. in the same cell as the training loop, in this case. The result is a single cell that's intimidatingly long and discourages interaction. Also, the fewer cells we have, the harder it is to write useful annotations in Markdown cells.

**Comment by ayulockin** [comment]
I get your point and have incorporated the suggestions in the colab notebook demonstrating the TensorFlow Integration. Give it a look and let me know if it works.

**Comment by charlesfrye** [comment]
Thanks for handling this, @ayulockin
