### ISSUE TITLE
Colab wandb.sweep() no attribute '_jupyter_login'

### ISSUE THREAD

**Issue by simonbogh** [wandb/examples#26]
Looking at examples for running sweeps in Google Colab and it throws the error below when running the standard initialization from https://docs.wandb.com/sweeps/python-api without calling `wandb.login()` first. The same goes for other wandb examples in Colab. A suggestion to update the documentation to include wandb.login()

```python
/usr/local/lib/python3.6/dist-packages/wandb/wandb_controller.py in sweep(sweep, entity, project)
    710         _api0 = InternalApi()
    711         if not _api0.api_key:
--> 712             wandb._jupyter_login(api=_api0)
    713     if entity:
    714         env.set_entity(entity)

AttributeError: module 'wandb' has no attribute '_jupyter_login'
```

wandb 0.10.1
Python 3.6

**Comment by charlesfrye** [comment]
Thanks for raising this, @simonbogh. We're tracking this issue internally and will deploy a fix in either 0.10.3 (incoming) or 0.10.4 (by next Monday).
