### ISSUE TITLE
How to use sweep on a machine with multiple gpu

### ISSUE THREAD

**Issue by clelouch** [wandb/examples#27]
Thanks for your great work. I knew that sweep can allocate tasks to different machine. But how to use sweep on a machine with multiple gpus? I want to train model with different hyperparameters on different gpu to take fully use of them. Thanks for your help.

**Comment by charlesfrye** [comment]
Hey @clelouch:

    Thanks! Always great to hear from folks making use of our tools.

     The exact way to solve this will depend on the details of your machine. You could solve it by launching separate [agents](https://docs.wandb.com/sweeps/quickstart#4-launch-agent-s) in environments where they have access to only a single GPU, e.g. by setting [CUDA_VISIBLE_DEVICES](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) to different values in each environment (e.g. shell).

    If you need more help, I recommend you reach out via our Intercom (the blue box in the lower-right-hand corner of the screen on our website). FYI, that's the channel we use to provide support to our users. The issue tracking here is for maintaining and improving these examples.
