### ISSUE TITLE
[Request]: Time Series Example in TensorFlow/Keras

### ISSUE THREAD

**Issue by lucifertrj** [wandb/examples#391]
### What is about?

I would like to contribute a Time Series code in TensorFlow or Keras examples. Please let me know if I can proceed with it...

**Comment by tcapelle** [comment]
Would love that! Some examples like the ones from `hfawaz` on Keras tutorials would be great to have!

**Comment by tcapelle** [comment]
That would be really cool! I encourage you to check [this](https://wandb.ai/stacey/sidereal/reports/Time-Series-Forecasting-in-W-B--VmlldzoyNzczMzcy) report on how to log the timeseries to the wandb workspace so we get the most out of the codebase. Also, I am sure that @soumik12345 could help you out on instrumenting your TF/Keras code with W&B.

**Comment by soumik12345** [comment]
Hi @lucifertrj 

I went through your article, and it looks great ❤️
Here are some pointers on instrumenting your example with Weights & Biases:

- You can log your `matplotlib` plots directly on WandB [[Reference](https://docs.wandb.ai/guides/track/log/plots#matplotlib-and-plotly-plots)]
- You can also directly log your dataframe to WandB as a `wandb.Table` using the following code snippet:
    ```python
    # Create a wandb Table from the pandas dataframe
    table = wandb.Table(dataframe=df)
    # Log the table to wandb
    wandb.log({"my_table": table})
    ```
    You can also refer to [this guide](https://docs.wandb.ai/guides/data-vis/tables) in order to learn more regarding how to utilize `wandb.Table` to visualize and analyze your data and results.
- Logging your metrics and model checkpoints to Wandb for a Keras workflow is very simple:
  - Use the [`WandbMetricsLogger`](https://docs.wandb.ai/guides/integrations/keras#experiment-tracking-with-wandbmetricslogger) callback to automatically log all your training and validation logs.
  - Use the [`WandbModelCheckpoint`](https://docs.wandb.ai/guides/integrations/keras#model-checkpointing-using-wandbmodelcheckpoint) callback to save the Keras model in SavedModel format or the model weights periodically and uploads them to WandB as a [`wandb.Artifact`](https://docs.wandb.ai/guides/artifacts) for model versioning.

You can refer to [this notebook](https://github.com/wandb/examples/blob/master/colabs/keras/Fine_tune_Vision_Transformer_using_KerasCV.ipynb) to check how to use the WandB callbacks for Keras.

We eagerly await your contribution 😃

**Comment by tcapelle** [comment]
What would be cool is to do a wandb.Report first. That way we can share that publicly on our platform https://wandb.ai/fully-connected

**Comment by soumik12345** [comment]
> What would be cool is to do a wandb.Report first. That way we can share that publicly on our platform https://wandb.ai/fully-connected

@lucifertrj 
Can you also convert this example into a Report like [this one](https://wandb.ai/gladiator/MONAI_Spleen_3D_Segmentation/reports/3D-Segmentation-with-MONAI-and-PyTorch-Supercharged-by-Weights-Biases---VmlldzoyNDgxNDMz)? We could publish it to our blog [Fully-Connected](https://wandb.ai/fully-connected) like mentioned by @tcapelle. You can check out [this guide](https://docs.wandb.ai/guides/reports) to learn how to write such cool reports.

**Comment by lucifertrj** [comment]
Sorry for the delay. This weekend I will open the PR. Closing the issue as of now
