### ISSUE TITLE
[Request]:  How to access best model and best paramenters from sweep?

### ISSUE THREAD

**Issue by slvcsl** [wandb/examples#406]
### Accessing best model and configuration
Hi! I am trying to use sweep starting from the quickstart and [sweeps-python](https://github.com/wandb/examples/tree/master/examples/wandb-sweeps/sweeps-python)/sweep.py example.

How do I access the best model / best config in the code once the selection is finished? I can see the visualization, but what about the code?

Thanks for the incredible work!

**Comment by scottire** [comment]
Here's a programmatic way to get the best run from a sweep: https://docs.wandb.ai/guides/track/public-api-guide#get-the-best-run-from-a-sweep

```python
import wandb
api = wandb.Api()

sweep = api.sweep("<entity>/<project>/<sweep_id>")
best_run = sweep.best_run()

```
