### ISSUE TITLE
keras-cnn-fashion example fails at resume step

### ISSUE THREAD

**Issue by elyall** [wandb/examples#51]
When running the keras-cnn-fashion example, even for the first time, it tries to resume a previous run and fails. Commenting out the "if run.resumed: resume" code (`examples/examples/keras/keras-cnn-fashion/train.py` lines 58-62) makes everything work fine.

python=3.8.5
wandb=0.10.9

First fix importing keras.models.load_model (PR #50), then run:

```python
import wandb
import yaml
project_name='test'
config_yaml = 'sweep-bayes-hyperband.yaml'
with open(config_yaml) as file:
    config_dict = yaml.load(file, Loader=yaml.FullLoader)
sweep_id = wandb.sweep(config_dict, project=project_name)
wandb.agent(sweep_id, project=project_name)
```

Returns:

```
RESUMING
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    model = load_model(wandb.restore("model-best.h5").name)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by charlesfrye** [comment]
looks like the resume bug is actually caused by the import bug -- the failure of the first attempt to resume generates a run with no `model-best.h5` file, returning a `None`.

i'll make my own fix that takes just your first commit there. i'm also gonna lint the code while im at it. thanks @elyall!
