### ISSUE TITLE
[Bug]: Colab x Weights & Biases Keras Callbacks not working

### ISSUE THREAD

**Issue by Esmedd** [wandb/examples#524]
### Tell us what happened?

Example - Use_WandbEvalCallback_in_your_Keras_workflow.ipynb

Error message at cell 2

```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-3d5089b1fc8b>](https://localhost:8080/#) in <cell line: 10>()
      8 # Weights and Biases related imports
      9 import wandb
---> 10 from wandb.keras import WandbMetricsLogger
     11 from wandb.keras import WandbModelCheckpoint
     12 from wandb.keras import WandbEvalCallback

ModuleNotFoundError: No module named 'wandb.keras'
```

This has also happened in other, personal colabs despite restarting the kernel after install, running uninstall/install, upgrading etc. Also have tried pip3 to no avail.
![Screenshot 2024-05-08 at 16 33 15](https://github.com/wandb/examples/assets/145558725/b0c4c341-ae5d-4a58-9362-8e68db5c7fcc)
![Screenshot 2024-05-08 at 16 33 24](https://github.com/wandb/examples/assets/145558725/25eff065-7013-4ca4-96f7-1639fdb23ef7)
<img width="1143" alt="Screenshot 2024-05-08 at 16 34 47" src="https://github.com/wandb/examples/assets/145558725/cfdecc4c-6f77-4f0d-a641-a7b8103db0fd">

**Comment by tcapelle** [comment]
cc @soumik12345

**Comment by tcapelle** [comment]
If you revert to `wandb<0.17` it works, I will check where are those imports now and update the colab

**Comment by Esmedd** [comment]
Great thanks, it works now :)
