### ISSUE TITLE
Reference to fastai2 should be fastai2

### ISSUE THREAD

**Issue by tvetterli-fn** [wandb/examples#63]
In the fastai section of the README, the import of fastai is as follows `from fastai2.callback.wandb import WandbCallback`. fastai2 has been released and the import could be `from fastai.callback.wandb import WandbCallback`.

- fastai code [(version 2)](https://github.com/fastai/fastai/blob/master/fastai/callback/wandb.py)
- fastai1 deprecation [at the top of the README](https://github.com/fastai/fastai)

Thanks!

**Comment by charlesfrye** [comment]
This has been fixed: https://github.com/wandb/examples/commit/8b9a701fb8df08dd975e41b4b26c7749389177db

Thanks for pointing it out!

**Comment by tvetterli-fn** [comment]
I'll do my own fork next time :P
