### ISSUE TITLE
'wandb' in YOLOV4

### ISSUE THREAD

**Issue by akshat-suwalka** [wandb/examples#77]
Hi everyone!

Can anyone help me to know that How can we train custom model using 'wandb' feature in YOLOV4-tiny?  We can easily use 'wandb' in YOLOV5 but how to integrate 'wandb' in YOLOV4?

**Comment by charlesfrye** [comment]
Hey Akshat!

YOLOv4 is available through Ultralytics' YOLOv3 implementation ([details here](https://github.com/ultralytics/yolov3/issues/1137)).

That implementation [includes wandb logging](https://github.com/ultralytics/yolov3/issues/1574), though the feature set is I believe different to (less than?) what we have in the v5 implementation.
