### ISSUE TITLE
Data hand-off

### ISSUE THREAD

**Issue by pmirallesr** [wandb/examples#78]
I have a private wandb project with hundreds of runs. I would like to hand off that data to another user i.e. transfer "ownership" of the project to him. Is this a supported use case? Is it supported for free accounts?

To be clear this is a one time hand-off, not an ongoing collaboration. Whether I retain a copy of the data or not is also irrelevant to me. The closes alternative I've found is downloading a csv with the data for all runs then transferring that file, but I don't think the other user can then make that into a wandb project of his own

Thanks for your time!

**Comment by charlesfrye** [comment]
Hi Pablo! I'm pretty sure we can help you with this. Get in contact with our support team via Intercom (the speech bubble in the corner of the webpage; turn off AdBlocker if you don't see it) and they'll get this sorted out for you.

Cheers,
Charles
