### ISSUE TITLE
Change program name

### ISSUE THREAD

**Issue by ShivanshuPurohit** [wandb/examples#81]
Rather than run `python train.py`, I want to run a shell script `./script.py train.py -d configs config1.yml config2.yml`. Do I simply change the `program` variable in the sweep for that?

**Comment by charlesfrye** [comment]
So long as the program is a Python script, changing `program` should work fine. If you want to make sure that other information, e.g. those config files, are passed separately from the hyperparameter arguments sent by the sweep, you'll want to review the [docs on Sweep command structure configuration](https://docs.wandb.ai/guides/sweeps/configuration#command) and make additional changes as needed.
