### ISSUE TITLE
Single value in yaml not passed as argument

### ISSUE THREAD

**Issue by beabevi** [wandb/examples#85]
Hi,

since yesterday night when performing `wandb sweep` parameters with a single value such as `epochs` [here](https://github.com/wandb/examples/blob/master/examples/pytorch/pytorch-cnn-fashion/sweep-grid-hyperband.yaml#L16) are not passed as argument to the process.

```
2021-08-19 10:11:38,946 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python train.py --channels_one=18 --channels_two=28 --dropout=0.5 --learning_rate=0.005
```

I think this is a server-side change that has happened recently.

**Comment by dannygoldstein** [comment]
Hi, this is fixed now in production as of 10:43 AM pacific time this morning (8/19/2021)
