### ISSUE TITLE
Using public api delete function doesnt delete all files

### ISSUE THREAD

**Issue by skyprince999** [wandb/examples#92]
I am using wandb to log the output of my experiments. This unfortunately creates a large number of files on the wandb server. Since they are image files & the log files of the experiment, they soon cross the free limit of 100GB. As such I am trying to delete them using the sample provided via your documentation. 

```
run_name = "run_name"

run = api.run("<org_name>/<project_name>/" + run_name)

files = run.files()
for file in tqdm(files):
  if file.name.endswith('.png'):
    file.delete()
```

All files are not deleted in a single run. I believe this is because of some time-outs in the api. Is it possible to send that as an error, so tht I can place a sleep routine & then call the api again. Right now its simply ending the loop w/o any errors. 

I have shared this with your support team. Though they have tried to support my case, it has not resulted in any positive outcome. Since I still have to run the same code block number of times. 

[wandb_log.log](https://github.com/wandb/examples/files/7273015/wandb_log.log)

**Comment by anmolmann** [comment]
Hi @skyprince999, could you try adjusting `WANDB_HTTP_TIMEOUT`var in your env (in seconds; needs to be an integer). The default value for this is 10. Please let us know if this helps resolve your issue or in case of any further assistance.

**Comment by skyprince999** [comment]
Bascially this approach has not worked for me. I have around 200+ files (image files) in each run. Sice this takes space on Wandb servers (and I am  charged for it! ) I wanted to remove the unnecessary files. 

Increasing the timeout as suggested by @anmolmann didn't solve it, since after completing one loop, the API was only able to delete around less than half of the files. 

So I used a hacky approach of simply running the loop multple times. Adding a gist to the approach that I have taken. 

https://gist.github.com/skyprince999/621e9ba1bc9e7c665a5cc7f58442d7b3

**Comment by anmolmann** [comment]
@skyprince999 , thanks for writing in. This has been escalated to our eng team.
Meanwhile, as an immediate step, you might want to delete the entire run and we’ll stop counting the underlying storage.

**Comment by tcapelle** [comment]
Did you found a solution on this issue? I will close this as it is not an "Examples" issue and more a wandb/client issue. Feel free to reopen an issue at https://github.com/wandb/client
