### ISSUE TITLE
Simple Scikit Integration Colab - Update for Classification Block

### ISSUE THREAD

**Issue by IndraP24** [wandb/examples#93]
* Issue:
Hi! I was surfing through the [wandb quickstarts](https://wandb.ai/quickstart) when I came across the Classification section of the [Scikit Integration example](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/scikit/Simple_Scikit_Integration.ipynb). The example uses the Wine Classification dataset and tries to do a Multi-Class Classification which is not yet supported by the **All-in-one: Classifier Plot** (implemented using `wandb.sklearn.plot_classifier()`). Check out the image below:

![image](https://user-images.githubusercontent.com/64627762/139555620-5b59ca0b-8fa7-489b-91f0-bafa7ec4dc94.png)

* Proposed Changes:
I want to update the Classification section just by using the Breast Cancer Dataset which can be found under `sklearn.datasets` instead of the Wine Dataset so that the **All-in-one: Classifier Plot** section runs without any error.

**Comment by charlesfrye** [comment]
Great suggestion @IndraP24!

In 613361a, I've rewritten the colab to use the WBCD dataset, as you suggested, and I also removed the [deprecated](https://twitter.com/ogrisel/status/1442894248488046595?s=21) Boston Housing dataset from the regression example, which we previously had done for our scripts in #91.

**Comment by IndraP24** [comment]
That's great! @charlesfrye
